# Generated by Django 2.2.4 on 2020-10-04 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventText', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Team')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.DurationField()),
                ('quarter', models.IntegerField()),
                ('down', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='board.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='board.Team'),
        ),
    ]
